---
- name: Config ELKvm with Docker
  hosts: elkservers
  remote_user: azdmin
  become: true
  tasks:

  - name: Increase memory usage
    sysctl:
      name: vm.max_map_count
      value: '262144'
      state: present
      reload: yes

  - name: Docker Install
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: pip3 Install
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Docker-Python Client
    pip:
      name: docker
      state: present

  - name: Download-Launch docker-elk container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044

  - name: Enable docker on boot
    systemd:
       name: docker
       enabled: yes